# Generated by Django 6.1 on 2026-08-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='intent',
            name='entities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='intent',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
