# Generated by Django 6.1 on 2026-08-22 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intents', '0002_intent_actions_intent_entities_intent_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('planned', 'Planned'), ('approved', 'Approved'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('intent_status_at_decision', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intent_approvals', to=settings.AUTH_USER_MODEL)),
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='intents.intent')),
            ],
        ),
    ]
